name: "Analyze code with SonarCloud"

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: Source
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup build environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SonarCloud Scan
        run: mvn sonar:sonar
        
