name: "Analyze code with SonarCloud"

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: Source
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup build environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: Source
          args: >
            -Dsonar.organization=engin-boot
            -Dsonar.projectKey=Engin-Boot_alert-to-care-s3b4
            -Dsonar.sources=src/     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
